### ISSUE TITLE
Performance improvement in animate method

### ISSUE THREAD

**Issue by RanzQ** [Nazariglez/pixi-animationloop#1]
I saw you are using `.bind()` here:

https://github.com/Nazariglez/pixi-animationloop/blob/master/src/AnimationLoop.js#L25

I'd suggest to move that into constructor like this:

```
this._animate = () => {
  ...
}
```

In babel, arrow functions keep `this` reference without `.bind()`. Now you are creating a new function on every frame and bound functions are slower anyway.

**Comment by Nazariglez** [comment]
Thanks @RanzQ! It's fixed now.
